# Generated by Django 4.0 on 2021-12-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_student_delete_studentextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
